version: "3"
services:
  app:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION=mongodb://db:27017/
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
